services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red-practica1
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    restart: unless-stopped

volumes:
  node_red_data: